# Generated by Django 3.2.12 on 2022-04-08 05:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
