# Generated by Django 3.2.12 on 2022-04-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience',
            field=models.IntegerField(),
        ),
    ]
